import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "components/common/Footer";
import Header from "components/common/Header";
import BootstrapClient from "./components/BootstrapClient";
import "./global.css";
config.autoAddCss = false;

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body>
            <Header />
            {children}
            <BootstrapClient />
            <Footer />
         </body>
      </html>
   );
}
