import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import dynamic from "next/dynamic";
import { ReactNode } from "react";
import "./global.css";

// NoSSR component
const Toaster = dynamic(() => import("./NoSSR/HotToast"), { ssr: false });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

interface RootLayoutProps {
   children: ReactNode;
}
export default function RootLayout({ children }: RootLayoutProps) {
   return (
      <html lang="en">
         <Toaster />
         <body>{children}</body>
      </html>
   );
}
