import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "components/common/Footer";
import Header from "components/common/Header";
import TanstackProvider from "context/TanstackProvider";
import BootstrapClient from "./components/BootstrapClient";
import "./global.css";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body>
            <TanstackProvider>
               <Header />
               {children}
               <BootstrapClient />
               <Footer />
            </TanstackProvider>
         </body>
      </html>
   );
}
