import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { ReactNode } from "react";
import "./global.css";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

interface RootLayoutProps{
   children:ReactNode
}
export default function RootLayout({ children }:RootLayoutProps) {
   return (
      <html lang="en">
         <body>{children}</body>
      </html>
   );
}
